[[redirects]]
  from = "/"
  to = "https://al-postel.vercel.app/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://al-postel.vercel.app"